# Generated by Django 3.0.3 on 2020-08-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200810_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='thoughtuser',
            name='text_en',
            field=models.CharField(max_length=360, null=True, verbose_name='think_text'),
        ),
        migrations.AddField(
            model_name='thoughtuser',
            name='text_ru',
            field=models.CharField(max_length=360, null=True, verbose_name='think_text'),
        ),
        migrations.AddField(
            model_name='thoughtuser',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='think_title'),
        ),
        migrations.AddField(
            model_name='thoughtuser',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='think_title'),
        ),
    ]
