# Generated by Django 3.0.3 on 2020-08-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_commentrset_commentuset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentuset',
            name='article',
        ),
        migrations.AlterField(
            model_name='archiveuser',
            name='type',
            field=models.IntegerField(choices=[(0, 'Folder'), (1, 'Post')], verbose_name='archive_type'),
        ),
        migrations.DeleteModel(
            name='Commentrset',
        ),
        migrations.DeleteModel(
            name='CommentUset',
        ),
    ]
