# Generated by Django 3.1.1 on 2020-10-28 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20200831_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrauser',
            name='filter',
        ),
        migrations.RemoveField(
            model_name='extrauser',
            name='icon_color_1',
        ),
        migrations.RemoveField(
            model_name='extrauser',
            name='icon_color_2',
        ),
        migrations.RemoveField(
            model_name='extrauser',
            name='icon_color_3',
        ),
        migrations.RemoveField(
            model_name='extrauser',
            name='icon_id',
        ),
        migrations.RemoveField(
            model_name='extrauser',
            name='karma',
        ),
        migrations.RemoveField(
            model_name='extrauser',
            name='money',
        ),
        migrations.RemoveField(
            model_name='extrauser',
            name='progress',
        ),
    ]
