# Generated by Django 3.1.1 on 2020-10-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20201028_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrauser',
            name='back_id',
            field=models.IntegerField(choices=[(0, 'Icon0'), (1, 'Icon1'), (2, 'Icon2')], default=0, verbose_name='Background ID'),
        ),
        migrations.AddField(
            model_name='extrauser',
            name='filter',
            field=models.TextField(blank=True, null=True, verbose_name='filter'),
        ),
        migrations.AddField(
            model_name='extrauser',
            name='icon_color_1',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Color 1'),
        ),
        migrations.AddField(
            model_name='extrauser',
            name='icon_id',
            field=models.IntegerField(choices=[(0, 'Icon0'), (1, 'Icon1'), (2, 'Icon2'), (3, 'Icon3'), (4, 'Icon4'), (5, 'Icon5'), (6, 'Icon6'), (7, 'Icon7'), (8, 'Icon8'), (9, 'Icon9'), (10, 'Icon10')], default=0, verbose_name='Icon ID'),
        ),
        migrations.AddField(
            model_name='extrauser',
            name='karma',
            field=models.IntegerField(default=0, verbose_name='Karma'),
        ),
        migrations.AddField(
            model_name='extrauser',
            name='money',
            field=models.IntegerField(default=0, verbose_name='Money'),
        ),
        migrations.AddField(
            model_name='extrauser',
            name='progress',
            field=models.ManyToManyField(blank=True, to='profiles.Progress'),
        ),
    ]
