# Generated by Django 3.1.1 on 2020-10-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20201028_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrauser',
            name='back_id',
            field=models.IntegerField(choices=[(0, 'Back0'), (1, 'Back1'), (2, 'Back2')], default=0, verbose_name='Background ID'),
        ),
    ]
