# Generated by Django 3.1.1 on 2020-10-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20201028_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrauser',
            name='icon_color_1',
            field=models.CharField(default='#d4d4d8,#22222e', max_length=50, verbose_name='Color'),
        ),
    ]
