# Generated by Django 3.1.1 on 2020-10-28 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20201028_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extrauser',
            old_name='icon_color_1',
            new_name='icon_color',
        ),
    ]
