# Generated by Django 3.1.1 on 2020-10-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20201028_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrauser',
            name='back_id',
            field=models.IntegerField(choices=[(0, 'Back0'), (1, 'Back1'), (2, 'Back2')], default=1, verbose_name='Background ID'),
        ),
        migrations.AlterField(
            model_name='extrauser',
            name='icon_id',
            field=models.IntegerField(choices=[(0, 'Icon0'), (1, 'Icon1'), (2, 'Icon2'), (3, 'Icon3'), (4, 'Icon4'), (5, 'Icon5'), (6, 'Icon6'), (7, 'Icon7'), (8, 'Icon8'), (9, 'Icon9'), (10, 'Icon10')], default=1, verbose_name='Icon ID'),
        ),
    ]
