# Generated by Django 3.1.1 on 2020-10-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20201028_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrauser',
            name='back_id',
            field=models.IntegerField(choices=[(1, 'Back1'), (2, 'Back2'), (3, 'Back3')], default=1, verbose_name='Background ID'),
        ),
    ]
