# Generated by Django 3.1.1 on 2020-11-08 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0016_auto_20201028_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrauser',
            name='icon_id',
            field=models.IntegerField(choices=[(0, 'Icon0'), (1, 'Icon1'), (2, 'Icon2'), (3, 'Icon3'), (4, 'Icon4'), (5, 'Icon5'), (6, 'Icon6'), (7, 'Icon7'), (8, 'Icon8'), (9, 'Icon9'), (10, 'Icon10')], default=8, verbose_name='Icon ID'),
        ),
        migrations.CreateModel(
            name='CommentThinkUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='think_title')),
                ('text', models.CharField(max_length=360, verbose_name='think_text')),
                ('pud_date', models.DateTimeField(verbose_name='think_pud_date')),
                ('think', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.thoughtuser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
