# Generated by Django 3.1.1 on 2020-11-09 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20201108_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentthinkuser',
            name='think',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='comment_article', to='profiles.thoughtuser'),
        ),
    ]
