# Generated by Django 3.1.1 on 2020-11-12 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_auto_20201109_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thoughtuser',
            old_name='connect',
            new_name='user',
        ),
    ]
