# Generated by Django 3.1.1 on 2020-11-13 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_auto_20201112_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentthinkuser',
            name='title',
        ),
        migrations.RemoveField(
            model_name='thoughtuser',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='thoughtuser',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='thoughtuser',
            name='title',
        ),
        migrations.RemoveField(
            model_name='thoughtuser',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='thoughtuser',
            name='title_ru',
        ),
    ]
