# Generated by Django 3.1.1 on 2020-11-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_auto_20201113_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrauser',
            name='level',
            field=models.IntegerField(default=0, verbose_name='Level'),
        ),
    ]
