# Generated by Django 3.1.1 on 2020-11-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_extrauser_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrauser',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Level'),
        ),
    ]
