# Generated by Django 3.1.1 on 2020-12-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_auto_20201117_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrauser',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Phone'),
        ),
    ]
